### ISSUE TITLE
haxelib release for Haxe 3.3.0

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/dox#167]
We'll need a dox haxelib release soon.

While we're at it, should we transfer dox to HaxeFoundation github?

**Comment by markknol** [comment]
I think it is ready to go? 
I don't have haxelib knowledge, who can pick this up? Don't forget to change "url" in haxelib.json to the new git location.

**Comment by Simn** [comment]
I'll do it when we're about to make the Haxe release.

**Comment by Simn** [comment]
@markknol: What do you want to get in before we make this release?

**Comment by markknol** [comment]
I think only https://github.com/HaxeFoundation/dox/issues/189 is important for the release.

**Comment by Simn** [comment]
That's a pretty big one though.

**Comment by markknol** [comment]
When does it need to be finished?

**Comment by Simn** [comment]
done
