### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/dox#168]
Can hxtemplo and hxparse be set to a fixed version?

**Comment by Simn** [comment]
Why?

**Comment by markknol** [comment]
Otherwise I never know if I'm up to date.

**Comment by Simn** [comment]
I don't mind as long as I don't actually have to do it!

**Comment by markknol** [comment]
So should I use a git version or does it only work with released versions?

**Comment by Simn** [comment]
I have no idea what you're asking...

**Comment by markknol** [comment]
ok i got it working so nevermind
