### ISSUE TITLE
markdown causes incorrect rendering in openfl docs 

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/dox#179]
I used the openfl xml's to test the template, since it has quite some documentation. The openfl docs has some weird indentation, which leads to not-nice looking things, some stuff is rendered suddenly in `<code>` tags because of markdown.

Is this something we can fix? Maybe openfl api docs does not use markdown. There is no official thing on how documentation with dox should be written. Would it be an idea to have an option to disable markdown in dox? Something like `--no-markdown`?

---

## example 1:  events in DisplayObject.hx
![image](https://cloud.githubusercontent.com/assets/576184/14810189/e0bb23f2-0b91-11e6-9bb3-c6f7186af782.png)

**source** https://github.com/openfl/openfl/blob/557f7c118e4c79eb9b3c1a4913b528280c2b008d/extern/openfl/display/DisplayObject.hx#L61-L72

---

## example 2: parameter in Graphics.hx

![image](https://cloud.githubusercontent.com/assets/576184/14810670/5890bc1e-0b94-11e6-889b-af9b4d9868d7.png)

**source** https://github.com/openfl/openfl/blob/557f7c118e4c79eb9b3c1a4913b528280c2b008d/extern/openfl/display/Graphics.hx#L338-L340

**Comment by Simn** [comment]
I suppose we could add a --no-markdown option.

**Comment by markknol** [comment]
You think changing it [here](https://github.com/HaxeFoundation/dox/blob/master/src/dox/JavadocHandler.hx#L38-L42) would do the trick?

**Comment by Simn** [comment]
Probably!
