### ISSUE TITLE
Default neutral theme

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/dox#189]
When generating the documentation for a library using the default theme you get a start page called "Haxe API documentation", all pages have a "(c) 2016 Haxe Foundation" footer and a header navigation with support links to the HaxeFoundation. The whole site looks like it is the official Haxe API documentation.

While one of course can create his own theme it would make a lot of sense to have a neutral default theme and a "Official Haxe API theme" that maybe inherits from this one. Otherwise every haxe library creator is required to create/maintain his own theme and constantly keep up with the changes in newer dox versions.

**Comment by markknol** [comment]
This is a good idea. I will pick this up. 

A complete new theme is maybe a bit too much. I am thinking to make the Haxe branded bar/footer only appear with a setting, and make a new bar with optional colors/logo with the given title. 

@Simn @ianharrigan It would be nice if we merge https://github.com/HaxeFoundation/dox/pull/185 soon, then I can pick this up.
