### ISSUE TITLE
Wildcard Inclusion Broken?

### ISSUE THREAD

**Issue by ashes999** [HaxeFoundation/dox#196]
I just updated haxelib from the previous latest version to dox 1.1.0. I had an include filter like `--include foo*` which included classes like `foo.Bar` and `foo.Baz`. No longer.

Instead, I have to use `--include foo`.

Is this intentional?

The [documentation page](https://github.com/HaxeFoundation/dox/wiki/Commandline-arguments-overview) could at least suggest how to do this; it just mentions "Add a path include filter".

**Comment by Simn** [comment]
Hmm, I don't think anything changed here really. The filter string is used as a regular expression and matched against type paths, so while `foo*` is a silly filter it should still work with a `foo.Bar` path. You probably want to use `^foo` anyway, but I'd like to know why `foo*` isn't working.

**Comment by ashes999** [comment]
`^foo` seems to work fine. Is this documented anywhere?

**Comment by Simn** [comment]
Command line has `[-in | --include] <regex>      : Add a path include filter` which should make it pretty clear that it's a regular expression. The wiki page strips that information though which is not ideal.

**Comment by markknol** [comment]
I've just added a new column 'expected value' there.

**Comment by Simn** [comment]
Thanks!

Any idea why `foo*` isn't working?

**Comment by markknol** [comment]
I did not touched that afaik, but I never used/tested it too, so I cannot say it worked before or not :confused:

**Comment by markknol** [comment]
I tested with my simple project but the * still seems to work.

@ashes999 can you double check?

**Comment by ashes999** [comment]
I can confirm that `foo*` doesn't include anything. I get `Generated 0 types in 1 packages`. With `^foo`, I get `Generated 20 types in 6 packages`.

Sorry. If you like, you can close this, because the work-around is simple enough.

**Comment by markknol** [comment]
Thanks. Still odd I tried several packages but "bla*" does the same as "bla" here.

Btw what is your project and do you have a link to your API docs? Just curious! :)

**Comment by ashes999** [comment]
Hi,

Unfortunately, I can't share that project or the docs here. If that changes, I'll come back and reopen this issue.

Cheers,
