### ISSUE TITLE
Type.field mapping broken for capitalized fields

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/dox#204]
The regex in `MarkdownHandler`'s `processCode()` appears to make the assumption that all fields start with a lowercase letter and that a path segment starting with an uppercase letter must be a type. This breaks in cases like `FlxObject.LEFT` (which should be pretty common).

**Comment by markknol** [comment]
I tested but `FlxObject.LEFT` should be recognized: http://try.haxe.org/#dFfb3 
The regexp only checks if there is an uppercase after a dot, so I dont understand how this goes wrong.

Can you provide me some xmls of the project and point me to cases which are broken?

**Comment by Gama11** [comment]
It's not about whether it's matched, it's in which capture group it ends up. You can see this better on http://regexr.com/:

![](http://i.imgur.com/GzuOHGU.png)

![](http://i.imgur.com/eBThHjH.png)

**Comment by markknol** [comment]
I would say `\b((\w+\.)*[A-Z]\w+)\b` would already do the trick?
