### ISSUE TITLE
Not all typedef fields are picked up

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/dox#205]
example: http://api.haxe.org/v/dev/haxe/macro/MetadataEntry.html
source:  https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/macro/Expr.hx#L668

It is documented, but not displayed.

**Comment by Gama11** [comment]
I think that's simply a limitation of the "quick structure declaration": https://github.com/HaxeFoundation/haxe/issues/3083

**Comment by markknol** [comment]
As far as I can see they are not declared any different then for example [Field](http://api.haxe.org/v/dev/haxe/macro/Field.html), which is also a typedef and the code comments are defined the same?

**Comment by markknol** [comment]
ah nevermind i see the difference
