### ISSUE TITLE
< characters not escaped for documentation

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/dox#207]
In the documentation the < is not escaped and shows the actual html

For example <iframe>:
http://api.haxe.org/js/html/HTMLDocument.html#createIFrameElement

But this is generated:
https://github.com/HaxeFoundation/haxe/blob/development/std/js/html/HTMLDocument.hx
so it needs to be fixed in the generator

**Comment by Simn** [comment]
That would be a HaxeFoundation/haxe issue.
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
j/k :P

**Comment by markknol** [comment]
I already created a ticket here https://github.com/HaxeFoundation/html-externs/issues/5

**Comment by Simn** [comment]
Hmm right, I suppose we shouldn't escape it here and instead fix the actual source. Sorry for sending you around like that!

**Comment by markknol** [comment]
Also to complete this cross ticket reference party it was already mentioned here too https://github.com/HaxeFoundation/dox/issues/133

**Comment by MatthijsKamstra** [comment]
@Simn : not a problem
