### ISSUE TITLE
Pressing keys focuses the search box when I do not expect it to

### ISSUE THREAD

**Issue by binki** [HaxeFoundation/dox#208]
Pressing many key combinations causes the search box to be focused on http://api.haxe.org/. I find this quite annoying and bothersome as it really interrupts my normal workflow which works on every other site.

For example, on GitHub, I can click out of any textbox and press spacebar to scroll down a page or shift+spacebar to scroll up a page. Or I can select text and press ctrl+c to copy it. Or I can press ctrl+l to highlight my browser’s address bar and start typing something.

In dox, all of these key combinations cause the search box to be focused. This scrolls me away from what I was looking at often, and deselects any selected text in the documentation’s content.

While I would prefer the search box just be focused once on page load and never on any key press, I think that if you verify that no meta keys are being pressed before focusing the search box that would cover most cases. Another common thing websites do is *only* highlight the search box if the user types `/` (forward slash). As a Mozilla/Seamonkey/Firefox user, I find this annoying because, in that browser, `/` initiates a lightweight search-in-page (much like `less(1)`). But since it is very common in websites to overload this character, that would be more acceptable as I can always press ctrl+f for a more heavyweight search-in-page experience.

**Comment by Simn** [comment]
I agree we should restrict this to no-modifier situations, except allow shift + a-z still.

It doesn't hijack the ctrl combinations in Chrome though. Which browser are you using?

**Comment by binki** [comment]
I’m using Seamonkey which is Mozilla based and appears to be behaving the same as Firefox for this issue—so for all intents and purposes I am a Firefox user. There is a [mozilla bug discussing how mozilla is more permissive in letting webapps intercept keys](https://bugzilla.mozilla.org/show_bug.cgi?id=380637). In chrome if you use an unbound shortcut like ctrl+m you see the same exact behavior as on Mozilla-based browsers; it appears that chrome handles this by not sending a DOM event for the keypress if it happens to match a shortcut that chrome itself handles. Or if you put chrome into fullscreen mode (F11), ctrl+l gets seen by the webpage as chrome passes more keys through to the webpage in fullscreen mode.
