### ISSUE TITLE
Support "inline" functions

### ISSUE THREAD

**Issue by madneon** [HaxeFoundation/dox#225]
The dox seems to omit `inline` functions, is there a way to include them as normal functions?

> 
>     /** This function will be omitted in documentation. **/
>     public inline function Test1() {
>         // do some important stuff ...
>     }

**Comment by Gama11** [comment]
Try defining `--no-inline` when creating the xml.

**Comment by madneon** [comment]
@Gama11 That totally works!
If thats the normal way of generating dox, the Issue can be closed. But... it could be useful if there is some mark on documented function, that this function is inlined - just like "read only", "static" labels etc.

**Comment by Gama11** [comment]
I'm actually not sure why this is necessary for you. You might be missing some other flags like `-D doc-gen`?

**Comment by madneon** [comment]
@Gama11 I was missing it indeed... I think those informations should be included in Wiki.

**Comment by Gama11** [comment]
It is mentioned: https://github.com/HaxeFoundation/dox/wiki/Generating-documentation-XML-files-using-Haxe

**Comment by markknol** [comment]
I've also added this to the readme https://github.com/HaxeFoundation/dox/commit/8a06337857bc9331d3ff74dc69f8e4bb6dc8afb6
