### ISSUE TITLE
Add hook for files inclusion in header template

### ISSUE THREAD

**Issue by shsh999** [HaxeFoundation/dox#226]
When creating a custom template, including additional files in the header requires copying the whole header.mtt file and adding them manually.

Please add a hook that allows inclusion of additional files such as scripts without having to override the template file.

Thank you very much!

P.S. if such thing is possible, I would be grateful if that would be added to the documentation, as I was unable to find anything.

**Comment by Gama11** [comment]
Something like `use`? https://github.com/HaxeFoundation/dox/blob/master/themes/default/templates/main.mtt#L13

**Comment by shsh999** [comment]
yes, inside the <head> tag itself...
something like:

`::use "header-hook.mtt"::::end::`

just above the </head> tag in `header.mtt`

with an empty `header-hook.mtt` in the default theme

**Comment by Simn** [comment]
Sounds good to me.

... though we could probably argue about the name for a while.

**Comment by shsh999** [comment]
the name is not important :-)

**Comment by Gama11** [comment]
There's already `styles.css` and `extra-styles.css`, mabye the naming should be consistent with that?

**Comment by shsh999** [comment]
do you mean something like `extra-headers.mtt`?

**Comment by Gama11** [comment]
Yes, something like that.

**Comment by shsh999** [comment]
sounds good do me

**Comment by markknol** [comment]
This seems to be done 👍 Please reopen if there is something left to do.
