### ISSUE TITLE
eval-only classes have no fields

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/dox#232]
http://api.haxe.org/v/dev/eval/vm/Gc.html
http://api.haxe.org/v/dev/eval/vm/Context.html

The fields exist in the XML, so it must be filtered at some point. I tried looking at it but couldn't find out what's going on yet.

**Comment by markknol** [comment]
Isnt it the case that eval should be defined as a platform somewhere?

**Comment by Simn** [comment]
I don't think you have to define platforms explicitly as long as there's a xml for them with platform.xml. But I'm not sure...

**Comment by markknol** [comment]
Is there a eval.xml? Because I dont see that is the platform dropdown?

**Comment by Simn** [comment]
It's generated as macro.xml

**Comment by Simn** [comment]
Fixed by https://github.com/HaxeFoundation/dox/commit/86716ae2fb74d3420273323904461300dbf90957, https://github.com/HaxeFoundation/haxe/commit/4d6e7e758045c6c5089c27ef0974a28e570b9cd0 and https://github.com/Simn/hxtemplo/commit/4b9ec0c07e9ec619c7c414c3a72af4be63d820cc.

**Comment by markknol** [comment]
http://api.haxe.org/v/dev/eval/vm/Context.html still does look weird but I think you need to put a linebreak after ```
