### ISSUE TITLE
Incorrect signatures on some abstracts

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/dox#244]
Since last update (well, I *think* this is a recent regression, but I might be wrong), some abstracts have wrong signatures on the generated documentation.

See [Vector](https://api.haxe.org/haxe/ds/Vector.html), for example:

* `map<S> (this:VectorData<T>):Vector<S>` instead of `map<S>(f:T->S):Vector<S>`
* `sort<T> (this:VectorData<T>):Void` instead of `sort<T>(f:T->T->Int):Void`
* etc.

**Comment by elnabo** [comment]
Same for the new [EnumValue](https://api.haxe.org/v/development/EnumValue.html)

Furthermore the incorrect fields are also duplicated as static.

**Comment by elnabo** [comment]
I was looking at the documentation, and saw that the problems listed seems fixed.

**Comment by kLabz** [comment]
Indeed :+1:
