### ISSUE TITLE
Missing methods from interfaces

### ISSUE THREAD

**Issue by Sunjammer** [HaxeFoundation/dox#247]
For some reason this interface...
```Haxe

interface IRenderTarget{
	function resize(w:Int, h:Int, flags:Int = -1):IRenderTarget;
	function bind():IRenderTarget;
	function release():IRenderTarget;
	function destroy():IRenderTarget;
	function getColorTexture():Int;
}
```
...only outputs a page with entries only for bind, getColorTexture and release. I've tried altering it in various ways but for some reason nothing takes. 

![capture](https://user-images.githubusercontent.com/249115/51967744-70dd5000-2470-11e9-8f74-f466df8a6f4c.PNG)

I'm also seeing some DCE-like behavior where interfaces and classes that aren't directly used are seemingly stripped from the docs. This with `-dce no` set.

**Comment by Sunjammer** [comment]
Yes, the xml is missing those methods. I'll use the --macro include approach, I was just wondering if the DCE might be related to my other problem

**Comment by Gama11** [comment]
I don't see how, if it's disabled.

When putting that interface into `TestClass.hx` in this repo and running `test.hxml`, it seems to work as expected:

![](https://i.imgur.com/H0onhcw.png)

**Comment by Sunjammer** [comment]
Well, that sucks. I have no idea why the xml is missing my methods :(

**Comment by Gama11** [comment]
Hm.. well, either way, it wouldn't be an issue with dox if it's already missing from the XML that Haxe generates. Let me know if you find a way to isolate it so it can be reproduced.
