### ISSUE TITLE
Handle @:noCompletion as @:dox(hide)?

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/dox#250]
We have many, many, many `@:dox(hide) @:noCompletion` meta on fields and properties within OpenFL.

Should `@:noCompletion` be handled as `@:dox(hide)`, or should it be an option?

**Comment by Gama11** [comment]
Hm, yeah, I guess the ideal case would be to have a meta with a more general name like `@:hide` / `@:hidden`... Not sure how realistic it is to deprecate `@:noCompletion`, but if typed metadata is ever implemented, that might be a good time to think about a better approach.

In the meantime, I doubt it would do much harm if `@:noCompletion` implied `@:dox(hide)`, as long as an explicit `@:dox(show)` still works.

**Comment by jgranick** [comment]
I'd _love_ if there was a way to alias meta-data

For example:

```haxe
@:fileXml('tags="haxe,release"')
@:noDebug
```

If there was some way we could alias this as @:cppNoDebug or something would be nice

**Comment by Gama11** [comment]
Hm... I had the idea of aliasing metadatas using `typedef` when I talked to @Simn about typed metadata recently. I hadn't considered the case of aliasing _multiple_ metadatas, but that should probably be supported too if that does get implemented.

Anyway, getting a bit off-topic.
