### ISSUE TITLE
Feature request: Link to external API docs

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/dox#251]
The OpenFL documentation links to types from Lime and Haxe.

It would be ideal if we could flag package paths to link to external Dox generated documentation sources, so https://api.openfl.org/openfl/utils/Future.html can link to  https://api.lime.software/lime/app/Future.html or core types (such as String) can link to the Haxe docs (such as https://api.haxe.org/String.html)

**Comment by Gama11** [comment]
I'm still maintaining a dox fork for Flixel just to make "View Source" link work across multiple repos / libs, which seems somewhat related to this.

**Comment by Gama11** [comment]
As of 1.4.0, it's possible to use dox as a library and override `Api.getSourceLink()` to do whatever you need to. Usage example in flixel-docs here:

https://github.com/HaxeFlixel/flixel-docs/blob/c2b874a9e88d1997723f8a38bdc92c2242b50ece/api/dox/Main.hx
