### ISSUE TITLE
Documentation sometimes link to lua specific page instead of haxe one

### ISSUE THREAD

**Issue by elnabo** [HaxeFoundation/dox#252]
There is a problem with the documentation in https://api.haxe.org/sys/io/File.html

`See sys.FileSystem for the complementary file system API.`

link to https://api.haxe.org/lua/lib/luv/fs/FileSystem.html#FileSystem instead of https://api.haxe.org/sys/FileSystem.html

**Comment by Gama11** [comment]
This particular case no longer seems to reproduce, but that might just be a coincidence. Closing in favor of https://github.com/HaxeFoundation/dox/issues/264 which still does reproduce.
