### ISSUE TITLE
haxe-doctest integration?

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/dox#254]
https://github.com/vegardit/haxe-doctest/issues/8

**Comment by Gama11** [comment]
Seems a bit too niche to have hardcoded support in dox. Maybe you can do something with a custom theme.

**Comment by nanjizal** [comment]
*'doctest is a module included in the Python programming language's standard library'* - first entry line in wikipedia

Niche and standard are normally considered opposite in meaning, if Haxe std library code used this style of format then contributors would probably be more likely to submit pulls with inline tests. I don't think I will have computer time to explore custom theme this summer, but good suggestion.

**Comment by Gama11** [comment]
Not sure how it's relevant that it's included in Python's std lib, we're talking about Haxe here.

**Comment by nanjizal** [comment]
Relevance was purely was that it was a proven workflow, the approach has been adapted to a few languages, in much the same way as javadoc's, alternative is a folder full of tests that are dislocated from the code and the location for each library varies, obviously disadvanages is that it clutters source when setup is big.
