### ISSUE TITLE
operator overloading support?

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/dox#255]
Is there any operator overloading support?

**Comment by markknol** [comment]
Is this a question about the dox tool or the manual on the haxe.org website? 

Please explain :)

**Comment by Gama11** [comment]
I think he just means "does dox show overloaded operators?". Which I don't think it does, unless the operator functions happen to be public.

**Comment by nanjizal** [comment]
Revised question:
**Is there any operator overloading support provided by **dox**, since I have tried and I do not see any?**
[see: Matrix1x2.add](https://nanjizal.github.io/geom/pages/geom/Matrix1x2.html#add)
The relevant part is not referenced so users do not know they can use **+**,
``` @:op(A + B) public static inline``` 
It seems that abstract classes are not really supported in dox yet public or private, I could add comment to readme perhaps?
Or perhaps it's implemented in a dev branch or I have missed something in my use case.

**Comment by Gama11** [comment]
Are you using dox from Haxelib? That's really outdated, you should install it from GitHub. That version should show metadata such as `@:op`.

>abstract classes

Haxe doesn't have abstract _classes_.

**Comment by nanjizal** [comment]
Ok updated to git, thanks. I presume will be released with Haxe4

**Comment by nanjizal** [comment]
But looking at the output I am not sure that it's ideal that it show the @:op(A + B) that's the code not really the actual use.. so not so user friendly for new haxe users where an explicit sentence might be more suitable?

**Comment by nanjizal** [comment]
'A + B' would be cleaner and not loose any clarity?
