### ISSUE TITLE
CPP builds cause a timeout on Travis

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/dox#256]
This used to work...

```
./bin/cpp/Dox -o bin/pages -i bin/xml

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself
```

https://travis-ci.org/HaxeFoundation/dox/jobs/548798142#L430

**Comment by Aurel300** [comment]
When I was testing this, the `main` function wasn't even ever reached, even if I change it to just `trace` one line. This also made it impossible to actually use hxcpp debugger (unless there is a way to start it without a function call in `main`). Maybe it's stuck in an infinite loop during static initialisation, somehow?

**Comment by Gama11** [comment]
Have you tried with a regular C++ debugger?

**Comment by Aurel300** [comment]
Just now, yes. I think it is getting stuck in a loop in `hxparse.Lexer.buildRuleset`:

https://github.com/Simn/hxparse/blob/f61faa2021f2abb85360f997ff72c4156c891adc/src/hxparse/Lexer.hx#L126-L133

The rules come from `templo` and the rulesets are indeed built during static initialisation, hence `main` is never reached.

**Comment by Aurel300** [comment]
Ok, this was actually fixed in https://github.com/HaxeFoundation/hxcpp/commit/8f4396940a8d580b35bc10a9557c0c35581a2900.
