### ISSUE TITLE
How to exclude top-level classes from docs?

### ISSUE THREAD

**Issue by CrazyFlasher** [HaxeFoundation/dox#262]
I run
`haxelib run dox -i build -o docs -ex hex -ex haxe -ex js -ex tink`

How to specify, that top-level classes should be also excluded?

**Comment by Aurel300** [comment]
If you want to only generate docs for a particular package `foo`, it might be easier to do `-ex "*" -in "^foo\.".

Alternatively, since the patterns are actually regular expressions, checking that the type begins with an uppercase letter might work? `-ex "^[A-Z]"`.

**Comment by CrazyFlasher** [comment]
Added `-ex "^[A-Z]"` but top level is still presents:
http://188.166.108.195/projects/domwires-haxe/docs/

**Comment by Aurel300** [comment]
And can you not use `-ex "*" -in "^com\."` ?

**Comment by CrazyFlasher** [comment]
Sorry, I didn't understand? What not to use?

**Comment by Aurel300** [comment]
You just want to generate docs for the `com` package, is that right?

Does just `-ex "*" -in "^com\."` work? This first excludes everything (`-ex "*"`), then includes back only the types beginning with `com.` (`-in "^com\."`).

**Comment by CrazyFlasher** [comment]
Hope, that didn't do the trick.
Here is my full script
```
-cp src
-D doc-gen
-lib hexinject:1.0.0-alpha.7
-xml build/js.xml
-js build/js_test.js
--macro include('com.domwires')
--no-output
-cmd haxelib run dox -i build -o docs -ex "*" -in "^com\."
```

**Comment by CrazyFlasher** [comment]
Hi. There was another issue in my script.
Currently, when I run: `haxelib run dox -i build -o docs -ex "*" -in "^com\."`
It throws error:
```
Called from ? line 1
Called from dox/Dox.hx line 101
Called from dox/Dox.hx line 57
Called from dox/Config.hx line 44
Called from dox/Config.hx line 122
Called from a C function
Called from dox/Config.hx line 127
Called from C:\Users\Jens\GitHub\haxe\std/neko/_std/EReg.hx line 22
Called from a C function
Called from C:\Users\Jens\GitHub\haxe\std/neko/_std/EReg.hx line 33
Uncaught exception - regexp.c(115) : Regexp compilation error : nothing to repeat in *
Error: Command failed with error 1
```

**Comment by CrazyFlasher** [comment]
This works fine!
`haxelib run dox -i build -o docs -in "^com\."`
Thanks!
