### ISSUE TITLE
Incorrect link to sys.io.File

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/dox#264]
https://api.haxe.org/sys/FileSystem.html
`See sys.io.File for the complementary file API.`

**Comment by jcward** [comment]
Issues found with sys links pointing to cs.system docs at:
- `sys.io.Process` at https://api.haxe.org/Sys.html#command
- `sys.io.File` at https://api.haxe.org/sys/FileSystem.html

**Comment by RblSb** [comment]
Fixed
