### ISSUE TITLE
abstract method parameters incorrect, 'this' is wrongly inserted for first param, for haxe4 ?

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/dox#266]
abstract method parameters incorrect ( tried dox 1.1.0, 1.2.0 and git ).
dox presents under **Methods**  
```haxe
inline applyScale (this:DualQ):DualQuaternion
```
code signature   
```haxe
    public inline
    function applyScale( s: Float ): DualQuaternion {
```
dox source
<https://nanjizal.github.io/geom/pages/geom/matrix/DualQuaternion.html#applyScale>
code source
<https://github.com/nanjizal/geom/blob/master/src/geom/matrix/DualQuaternion.hx#L119>

doc generation used
<https://github.com/nanjizal/geom/blob/master/generate.hxml>
<https://github.com/nanjizal/geom/blob/master/generateDoc.hxml>

This seems to be effecting other abstract classes. For instance.
<https://nanjizal.github.io/geom/pages/geom/matrix/Matrix3x3.html#getXY><https://github.com/nanjizal/geom/blob/master/src/geom/matrix/Matrix3x3.hx#L350>
  
This could be related to only haxe4 since I don't see similar errors in much older dox use ( 3 years back ) for instance.
<https://rawgit.com/nanjizal/triangulationsWebGLtest/master/doc/pages/triangulations/Edges.html#flipEdge>

**Comment by nanjizal** [comment]
If I compare the correctly displaying static method **scalar** with incorrect **applyScale** 
```xml
	<applyScale public="1" get="inline" set="null" line="118" static="1">
		<f a="this:s">
			<c path="geom.structure.DualQ"/>
			<x path="Float"/>
			<x path="geom.matrix.DualQuaternion"/>
		</f>
		<meta><m n=":impl"/></meta>
	</applyScale>
```
``` xml
	<scalar public="1" get="inline" set="null" line="131" static="1">
		<f a="s">
			<x path="Float"/>
			<x path="geom.matrix.DualQuaternion"/>
		</f>
		<haxe_doc>* allow scaling a DualQuaternion untested
     * usage:
     * var scaledDualQuaternion = DualQuaternion.scalar( 3 ) * dualQ;
     * source:  *http://roartindon.blogspot.com/2015/04/encoding-uniform-scale-in-quaternions.html</haxe_doc>
```

**Comment by nanjizal** [comment]
Long shot... it's not related to the as3 target changes in typecore.ml or filters.ml? https://github.com/HaxeFoundation/haxe/pull/8934/files

**Comment by nanjizal** [comment]
I have released the library wondering if there are any thoughts on fixes?

**Comment by Gama11** [comment]
I just noticed this in Flixel too: http://api.haxeflixel.com/flixel/util/FlxColor.html?

![](https://i.imgur.com/jkcrWvf.png)

I agree that this is probably a regression, pretty sure I would've noticed this if it was always happening.

**Comment by nanjizal** [comment]
Is there a mac version of this build I can grab to update doc's for some of my libraries?

**Comment by Gama11** [comment]
Not sure what you mean, dox uses Neko, so it works on any OS (or as of 1.4.0 `node` if available since that's much faster).

**Comment by nanjizal** [comment]
ah already new dox on haxelib 👍

**Comment by Gama11** [comment]
Ah. It was a dox bug (but it only happened when dox was built with Haxe 4, hence the regression).
