### ISSUE TITLE
Unable to make a doc

### ISSUE THREAD

**Issue by rboullerne** [HaxeFoundation/dox#270]
![image](https://user-images.githubusercontent.com/5578211/78122010-6cae1900-740c-11ea-9676-bc9d3bd088fb.png)

Hello, I tried to build a doc with dox, but someone someone decided that all installement of haxe should be at C:\Users\Jens\Roaming. :/

This happens after installing dox 1.4.0

**Comment by Gama11** [comment]
No, that's not what the error is about.

This happens when you try to run dox with a Neko version < 2.3.0, because the `run.n` was compiled with Haxe 4. Unfortunately you currently can't target older Neko versions with Haxe 4.

**Comment by rboullerne** [comment]
Does that mean I have to downgrade my haxe to use dox? :S

**Comment by Gama11** [comment]
No, it means you need to use the Neko version that was shipped with Haxe 4. You are currently using an older one.

**Comment by rboullerne** [comment]
Alright, thanks a lot !

**Comment by anissen** [comment]
I get the same error using Haxe (stable and nightly) through lix. How do I use the correct version of Neko to fix this issue?

**Comment by Gama11** [comment]
I think lix does not have a mechanism to update neko yet, so find where lix stores it, delete it, and it will grab the latest version next time you run something that needs neko.

**Comment by Gama11** [comment]
Also, if you installed dox through Haxelib, it will use `node` if it's in your PATH and recent enough. It's considerably faster for Dox than Neko.

**Comment by anissen** [comment]
I have the latest version of node installed but dox insists on using neko. If I delete neko, a new instance of neko is installed... of version 2.2.0 😕 
```
➜  cosy git:(master) ✗ node -v                                                          
v13.13.0

➜  cosy git:(master) ✗ haxelib run dox -i docs/docs.xml -o docs/pages
Neko seems to be missing. Attempting download ...
-> Done!
done
Called from C:\Users\Jens\AppData\Roaming/haxe/versions/af197e3/std/neko/_std/Date.hx line 126
Uncaught exception - load.c(357) : Primitive not found : std@date_utc_format(2)
Failed to invoke `haxelib run-dir dox /Users/nissen/haxe/haxe_libraries/dox/1.5.0/haxelib
```

**Comment by anissen** [comment]
If I manually download neko 2.3.0 from https://nekovm.org/download/ and replace `~/haxe/neko/` with it, it works. It's not pretty but it'll do for now. Thank you for your help @Gama11 👍

**Comment by anissen** [comment]
I guess node is only detected/used _after_ neko 2.2.0. After I upgraded to neko 2.3.0 it uses _node_ to run dox:
```
➜  cosy git:(master) ✗ ./scripts/docs.sh
Using Node.js version of dox...
Parsing docs/doc.xml
Processing types
..................
Generating navigation
Generating 404 page
Generating to docs/pages
..................
Generated 34 types in 1 packages
Copying resources from /Users/nissen/haxe/haxe_libraries/dox/1.5.0/haxelib/themes/default/resources
Done (0.594s)
```

**Comment by Gama11** [comment]
Are you sure your lix version was up to date? What the latest neko version currently is may be hardcoded in there somewhere.

Yes, the `run.n` still has to run first to invoke node.

**Comment by anissen** [comment]
> Are you sure your lix version was up to date? What the latest neko version currently is may be hardcoded in there somewhere.

That was it! Neko was [updated](https://github.com/lix-pm/lix.client/issues/100) from 2.2.0 to 2.3.0 on the 17th November 2019 and my version (15.5.4) was from August 2019. That clears it up, and I've now update to the latest version of lix. Thanks again for your help @Gama11 !

**Comment by thomasjwebb** [comment]
I'm having this issue. I'm using lix as part of an npm-based project, it's the latest lix and I even deleted other dependencies to make sure nothing else could be overwriting:

```json
  "devDependencies": {
    "lix": "^15.9.0"
  }
```

but `npx lix neko` shows `.../node_modules/.bin/neko` and if I run that, I get:

```
NekoVM 2.2.0 (c)2005-2017 Haxe Foundation
  Usage : neko <file>
```

Is lix incapable of installing the right version so that I have to do the manual step above?
