### ISSUE TITLE
API php.Generator page style is broken

### ISSUE THREAD

**Issue by okawa-h** [HaxeFoundation/dox#271]
see : https://api.haxe.org/php/Generator.html

API php.Generator page style is broken.
I am wondering whether to fix api.haxe.org or dox.

It would be nice to insert `display: block` on this line.
dox : https://github.com/HaxeFoundation/dox/blob/6f35db89dfe97ea533734f289762be64dbe4bd92/themes/default/resources/styles.css#L331

**Comment by okawa-h** [comment]
This problem is deeper.

**Comment by Gama11** [comment]
What do you mean?

**Comment by okawa-h** [comment]
I thought it was a simple problem. But it was another problem!

**Comment by Gama11** [comment]
Hm, after playing around with it for a bit, I don't think it's really worth it to fix this in dox. We should simply put JavaDoc tags at the end of doc comments where they belong. :)
