### ISSUE TITLE
incorrect html emitted for code with pipe

### ISSUE THREAD

**Issue by AlexHaxe** [HaxeFoundation/dox#277]
for ``` `&` ``` dox produces `<p><code>&amp;</code></p>` 
however for ``` `|` ``` it emits a ```<table><thead><th align="null">`</th><th align="null">`</th></thead><tbody></tbody></table>``` 

see https://api.haxe.org/haxe/macro/Binop.html#OpOr (see also OpBoolOr and OpAssignOp)

**Comment by Gama11** [comment]
That's a haxe-markdown issue: https://github.com/HaxeFoundation/haxe-markdown/issues/36
