### ISSUE TITLE
Constraints not listed in documentation

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/dox#283]
The method addShader is generated as :
https://heaps.io/api/h3d/mat/Pass.html#addShader

But it has a constraint on the T parameter which doesn't show in generated doc
```haxe
	public function addShader<T:hxsl.Shader>(s:T) : T { ... }
```

**Comment by Gama11** [comment]
Duplicates https://github.com/HaxeFoundation/dox/issues/274.
