### ISSUE TITLE
GitHub warns about "high severity" security concerns about JQuery 1.9.1

### ISSUE THREAD

**Issue by anissen** [HaxeFoundation/dox#289]
Caused by https://github.com/HaxeFoundation/dox/blob/master/themes/default/resources/jquery-1.9.1.min.js.

See e.g. https://github.com/anissen/cosy/security/dependabot:
![image](https://user-images.githubusercontent.com/879967/127221154-2d3c674c-c73a-46da-87c3-66318caa4cd1.png)

**Comment by Gama11** [comment]
https://github.com/anissen/cosy/security/dependabot gives me "page not found".

**Comment by Aurel300** [comment]
Perhaps it's a private repo? The solution is just to update jQuery though.

**Comment by anissen** [comment]
Ah, it's probably private to me as the repository owner. Anyways, it simply
shows the attached image.

**Comment by AcaiBerii** [comment]
JQuery 1.9.1 introduces a security vulnerability that allows executing untrusted XSS code. You really want to update JQuery unless it's not used.
