### ISSUE TITLE
sys.io.Process shows to cs.system.diagnostics.Process

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/dox#295]
![grafik](https://user-images.githubusercontent.com/44057030/155622423-0f26f9b1-f09c-4efb-834b-cd78286107ce.png)

**Comment by kLabz** [comment]
Seems to be fixed?
https://api.haxe.org/Sys.html#command

**Comment by lublak** [comment]
@kLabz yes :) its looks correct now
