### ISSUE TITLE
Ignore lib on xml generation?

### ISSUE THREAD

**Issue by Mimerr** [HaxeFoundation/dox#298]
Is it possible to ignore included libraries on doc-gen xml creation?

`haxe -D doc-gen -xml build/xml/hl.xml -hl build/dummy.hl -main Main -cp src -lib abighelpfullib`

For example, the above will generate xml for everything I have in src but also everything from "abighelpfullib" which I don't really want. I just want my src files documentation.

Not sure if I am missing something obvious or this is just not meant to be possible?

**Comment by Simn** [comment]
You can use `--exclude` to exclude packages.
