### ISSUE TITLE
Abstract types: instance members are documented as static members.

### ISSUE THREAD

**Issue by cedx** [HaxeFoundation/dox#300]
I expect that instance members of an abstract type appear as instance ones. But `dox` incorrectly generates them as static members.

For example, the `Map` type in the Haxe API:
https://api.haxe.org/haxe/ds/Map.html

Or the `Locale` type in one of my projects:
https://github.com/cedx/intl.hx/blob/main/src/intl/Locale.hx (nearly all members are instance ones)
becomes
https://cedx.github.io/intl.hx/intl/Locale.html (all members are documented as static ones)

Haxe 4.2.5, Dox 1.6.0

**Comment by Simn** [comment]
Closed by #305
