### ISSUE TITLE
Support @inheritDoc or equivalent

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/dox#73]
Sometimes you have a base class/interface that has a documented method, then you override/implement that method in a subclass. It would be nice not to have to write documentation for that new method.

Example: https://aduros.com/flambe/api/flambe/display/EmitterSprite.html#draw might inherit the doc of https://aduros.com/flambe/api/flambe/display/Sprite.html#draw

Javadoc has an explicit @inheritDoc tag for this. Maybe we could even make it implicit if the override has no doc? I don't why you wouldn't want to inheritDoc in that case.

**Comment by wiggin77** [comment]
+1 for @inheritDoc support such that interface method documentation can be propagated to implementing classes.  Huge pita cutting and pasting these docs, then doing it again when the documentation changes.

**Comment by cmandlbaur** [comment]
This would be great to have, even if via @dpeek 's fix in #129

**Comment by Gama11** [comment]
This will be supported via compiler metadata: https://github.com/HaxeFoundation/haxe/pull/8854
