### ISSUE TITLE
Top level types should be hidden for platforms do not support these types

### ISSUE THREAD

**Issue by Atry** [HaxeFoundation/dox#79]
For example, `FileSystem` should be hidden in http://api.haxe.org/sys/index.html when the user choose `flash` platform.

**Comment by markknol** [comment]
The package `sys` is not displayed anymore in the treeview when platform is js, flash or flash8 in the new `haxe-api` theme. See https://github.com/dpeek/dox/pull/114

**Comment by Simn** [comment]
Could we apply this fix to the default theme as well?

**Comment by dpeek** [comment]
Can we all just vote to make the haxe-api theme the new default and delete the other themes? All in favour?

**Comment by markknol** [comment]
I vote for haxe-api as defaiut and remove the others (maybe keep the flambe one for @aduros ?) I'd like to add a extra flag to hide top menu bar. 

You can start with removing the "markknol" theme.

**Comment by dpeek** [comment]
@aduros are you happy to keep the flambe theme somewhere else? Just trying to minimise the number of themes we have to maintain (ideally to one!)

**Comment by Simn** [comment]
I feel a bit silly because I nagged him to release it for so long. Then again the haxe-api theme was made based on it, so it was still worth it.

**Comment by aduros** [comment]
I would be totally fine with that. I'm still using my custom template files from before the flambe theme was created, and haven't actually migrated to it :P

(Not for any reason besides lack of time. I'm looking forward to migrating to the sexy new default theme)

**Comment by markknol** [comment]
@simn this ticket can be closed?

**Comment by Simn** [comment]
You tell me?
